language: csharp
solution: HeartBeat.sln
install:
  - nuget restore HeartBeat.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release HeartBeat.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./HeartBeat/Common/bin/Debug/Common.dll
